# -*- coding:utf-8 -*-
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from networkapi.infrastructure import xml_utils

error_messages = {
    1: 'Falha ao acessar a fonte de dados',
    2: 'Falha ao executar o script. Causa: %s',
    3: 'Falha ao executar a leitura do XML de requisição. Causa: %s',
    4: 'Falha ao gerar o XML de resposta. Causa: %s',
    100: 'Tipo de equipamento não cadastrado',
    101: 'Model of equipment not registered',
    102: 'Group of equipment not registered',
    103: 'Identificador do tipo de equipamento é obrigatório',
    104: 'Identificador do modelo do equipamento é obrigatório',
    105: 'Nome do equipamento é obrigatório',
    106: 'Identificador do grupo do equipamento é obrigatório',
    107: 'Equipamento do grupo “Equipamentos Orquestração” somente poderá ser criado com tipo igual a “Servidor Virtual"',
    108: 'the VLAN name duplicated within an environment informed',
    109: 'Não existe número de VLAN disponível nos intervalos de %d até %d e de %d até %d para o ambiente informado',
    110: 'Ambiente com Divisão DC diferente de BE e FE',
    111: 'Type of network not registered',
    112: 'Environment not registered',
    113: 'O nome da VLAN é obrigatório',
    114: 'O identificador do ambiente é obrigatório',
    115: 'O identificador da VLAN é obrigatório',
    116: 'VLAN not registered',
    117: 'Equipment %s not registered',
    118: 'IP %s not registered for the equipment %s',
    119: 'IP not registered',
    120: 'IP already registered for the equipment',
    121: 'VLAN não validada',
    122: 'VLAN já ativada',
    123: 'The identifier of the IP is required',
    124: 'Healthcheck_expect não cadastrado',
    125: 'Invalid value of the finality',
    126: 'Invalid value of the client',
    127: 'Invalid value of the environment',
    128: 'Invalid value of the cache',
    129: 'Invalid value of the method_bal',
    130: 'Formato do valor do transbordo %s inválido',
    131: 'Valor do método de balanceamento inválido',
    132: 'Invalid value of the persistence',
    133: 'Valor do tipo do healthcheck inválido ou inconsistente em relação ao valor do healthcheck_expect',
    134: 'Valor do healthcheck inconsistente em relação ao valor do tipo do healthcheck',
    135: 'Invalid value of the timeout',
    136: 'Invalid value of the host',
    137: 'Invalid value of the maximum number of connections',
    138: 'Valor da variável porta_servico %s inválido',
    139: 'Não existe ligação no front cadastrada para a interface do equipamento',
    140: 'O sufixo do reals_name é obrigatório para criar ou alterar o vip %s do grupo virtual',
    141: 'Interface não cadastrada',
    142: 'Interface não está relacionada com o host',
    143: 'Interface do switch está com o campo protegida setado',
    144: 'A ligação no front da interface não tem nenhuma interface que representa um switch',
    145: 'O nome da interface é obrigatório',
    146: 'Equipamento já está cadastrado no grupo',
    147: 'O identificador do equipamento é obrigatório',
    148: 'Existe mais de um equipamento com o mesmo nome',
    149: 'Equipamento com nome duplicado',
    150: '%s',
    151: 'Valor do real %s inválido',
    152: 'Request VIP is not registered.',
    153: 'IP %s.%s.%s.%s not registered for the environment %s',
    154: 'O valor da indicação de ativo do usuário é inválido',
    156: 'Equipamento %s já está cadastrado no ambiente %s',
    157: 'Equipamento %s não está cadastrado para o ambiente %s',
    158: 'Tipo de roteiro %s não cadastrado',
    159: 'O identificador do grupo layer 3 é obrigatório',
    160: 'Grupo layer 3 %s não cadastrado',
    161: 'O identificador do ambiente lógico é obrigatório',
    162: 'Ambiente lógico %s não cadastrado',
    163: 'O identificador da divisão DC é obrigatório',
    164: 'Divisão DC %s não cadastrada',
    165: 'Roteiro %s não cadastrado',
    166: 'O nome da marca é obrigatório',
    167: 'Marca %s não cadastrada',
    168: 'O nome do grupo layer 3 é obrigatório',
    169: 'Nome %s já cadastrado para outro grupo layer 3',
    170: 'O protocolo é obrigatório',
    171: 'Tipo de acesso %s não cadastrado',
    172: 'O nome do ambiente lógico é obrigatório',
    173: 'Nome %s já cadastrado para outro ambiente lógico',
    174: 'O nome da divisão DC é obrigatório',
    175: 'Nome %s já cadastrado para outra divisão DC',
    176: 'O nome do tipo de rede é obrigatório',
    177: 'User %s not registered',
    178: 'O user do usuário é obrigatório',
    179: 'User %s já está cadastrado para outro usuário',
    180: 'User Group %s not registered',
    181: 'Nome do grupo de usuário é obrigatório',
    182: 'Grupo de usuário com o nome %s já cadastrado',
    183: 'Usuário %s já está cadastrado no grupo %s',
    184: 'Usuário %s não pertence ao grupo %s',
    185: 'Equipamento %s não pertence ao grupo %s',
    186: 'The IP of the request VIP %s could not be changed because the VIP is already created',
    187: 'Interface com o nome %s já cadastrada para o equipamento %s',
    188: 'Interface %s não está associada ao equipamento %s',
    189: 'Permissão administrativa %s não cadastrada',
    190: 'Roteiro %s não associado ao equipamento %s',
    191: 'Requisição de VIP %s não validada',
    192: 'Requisição de VIP %s já criada',
    193: 'Tipo de roteiro com nome %s já cadastrado',
    194: 'O identificador do tipo de roteiro é obrigatório',
    195: 'O nome do roteiro é obrigatório',
    196: 'O tipo de roteiro %s não pôde ser excluído porque tem roteiro associado',
    197: 'O roteiro %s não pôde ser excluído porque tem equipamento associado',
    198: 'Roteiro %s já está associado ao equipamento %s',
    199: 'A marca %s não pôde ser excluída porque tem modelo associado',
    200: 'O nome do modelo é obrigatório',
    201: 'O identificador da marca é obrigatório',
    202: 'O modelo %s não pôde ser excluído porque tem equipamento associado',
    203: 'Tipo de acesso com o protocolo %s já cadastrado',
    204: 'O tipo de acesso %s não pôde ser excluído porque tem equipamento associado',
    205: 'The fqdn is required',
    206: 'The user is required',
    207: 'The password is required',
    208: 'O identificador do tipo de acesso é obrigatório',
    209: 'Equipamento %s não está associado ao tipo de acesso %s',
    210: 'O valor da indicação de protegida da interface é obrigatório',
    211: 'O valor da indicação de protegida da interface é inválido',
    212: 'Interface da ligação front não cadastrada',
    213: 'Interface da ligação back não cadastrada',
    214: 'Interface %s não pôde ser excluída porque tem outra interface associada',
    215: 'Tipo de rede %s não pôde ser excluído porque tem rede associada',
    216: 'Divisão DC %s não pôde ser excluída porque tem ambiente associado',
    217: 'Ambiente lógico %s não pôde ser excluído porque tem ambiente associado',
    218: 'Grupo layer 3 %s não pôde ser excluído porque tem ambiente associado',
    219: 'Ambiente com o mesmo grupo layer 3, ambiente lógico e divisão DC já cadastrado',
    220: 'Ambiente %s não pôde ser excluído porque tem vlan ou equipamento associado',
    221: 'O nome do usuário é obrigatório',
    222: 'O e-mail do usuário é obrigatório',
    223: 'O valor da indicação de ativo do usuário é obrigatório',
    224: 'O usuário %s não pôde ser excluído porque tem event_log ou grupo associado',
    225: 'A indicação de leitura do grupo do usuário é obrigatória',
    226: 'A indicação de escrita do grupo do usuário é obrigatória',
    227: 'A indicação de edição do grupo do usuário é obrigatória',
    228: 'A indicação de exclusão do grupo do usuário é obrigatória',
    229: 'O valor da indicação de leitura do grupo do usuário é inválido',
    230: 'O valor da indicação de escrita do grupo do usuário é inválido',
    231: 'O valor da indicação de edição do grupo do usuário é inválido',
    232: 'O valor da indicação de exclusão do grupo do usuário é inválido',
    233: 'O identificador do roteiro é obrigatório',
    234: 'O identificador do usuário é obrigatório',
    235: 'O identificador do grupo de usuário é obrigatório',
    236: 'O nome do grupo de equipamento é obrigatório',
    237: 'A função da permissão administrativa é obrigatória',
    238: 'A indicação de leitura da permissão administrativa é obrigatória',
    239: 'A indicação de escrita da permissão administrativa é obrigatória',
    240: 'O valor da indicação de leitura da permissão administrativa é inválido',
    241: 'O valor da indicação de escrita da permissão administrativa é inválido',
    242: 'Equipamento %s já está associado ao tipo de acesso %s',
    243: 'O identificador da requisição de VIP é obrigatório',
    244: 'O valor da indicação de validado da requisição de VIP é inválido',
    245: 'O valor da indicação de vip_criado da requisição de VIP é inválido',
    246: 'A indicação de validado da requisição de VIP é obrigatória',
    247: 'A indicação de vip_criado da requisição de VIP é obrigatória',
    248: 'O identificador da permissão administrativa é obrigatório',
    249: 'O nome do tipo de roteiro é obrigatório',
    250: 'Roteiro com o nome %s e tipo de roteiro %s já cadastrado',
    251: 'Marca com o nome %s já cadastrada',
    252: 'Modelo com o nome %s e a marca %s já cadastrado',
    253: 'Tipo de rede com o nome %s já cadastrado',
    254: 'Grupo de equipamento com o nome %s já cadastrado',
    255: 'O identificador da interface é obrigatório',
    256: 'O identificador do tipo de rede é obrigatório',
    257: 'Permissão administrativa com grupo de usuário %s e função %s já cadastrada',
    258: 'Rights Group Equipment %s not registered',
    259: 'A indicação de leitura do direito grupo equipamento é obrigatória',
    260: 'A indicação de escrita do direito grupo equipamento é obrigatória',
    261: 'A indicação de alterar_config do direito grupo equipamento é obrigatória',
    262: 'A indicação de exclusão do direito grupo equipamento é obrigatória',
    263: 'O valor da indicação de leitura do direito grupo equipamento é inválido',
    264: 'O valor da indicação de escrita do direito grupo equipamento é inválido',
    265: 'O valor da indicação de alterar_config do direito grupo equipamento é inválido',
    266: 'O valor da indicação de exclusão do direito grupo equipamento é inválido',
    267: 'Direitos Grupo Equipamento com o grupo de usuário %s e o grupo de equipamento %s já cadastrado',
    268: 'O identificador dos direitos grupo equipamento é obrigatório',
    269: 'Parameter %s is invalid. Value: %s',
    270: 'The VIP %s could not be changed because the VIP has not been created',
    271: 'Groups of equipment registered with the IP of the VIP request is not allowed of acess.',
    272: 'List the Reals_priority  is higher or lower than list the real_server.',
    273: 'Lock wait timeout exceeded; try restarting transaction.',
    274: 'List the Reals_weight  is higher or lower than list the real_server.',
    275: 'The healthcheck_type parameter not exist.',
    276: 'The healthcheck_type parameter is not HTTP, then healthcheck and id_healthcheck_expect must be None.',
    277: 'The healthcheck_type parameter is HTTP, then healthcheck and id_healthcheck_expect must NOT be None.',
    278: 'List the ports  is higher or lower than list the real_server.',
    279: 'The VLAN name must be a string with a maximum of 50 characters and can not be empty.',
    280: 'The description of the VLAN must be a string with a maximum of 200 characters.',
    281: 'Network IPv4 is not registered.',
    282: 'The identifier RedeIPv4 is mandatory',
    283: 'Environment VIP not registered',
    284: 'There networkIPv4 associated with environment vip',
    285: 'There networkIPv6 associated with environment vip',
    286: 'Network IPv6 is not registered.',
    287: 'At least one of the parameters have to be informed to query',
    288: 'IP is not associated with the equipment',
    289: 'Option VIP is not registered.',
    290: 'Option vip is already associated with the environment vip',
    291: 'Option vip is not associated with the environment vip',
    292: 'IPv6 %s not registered for the environment %s',
    293: 'Vlan is currently in active/deployed state. It needs to be undeployed before deletion.',
    294: 'Invalid Environment Configuration or not registered',
    295: 'Unavailable address to create a NetworkIPv4',
    296: 'Unavailable address to create a NetworkIPv6',
    297: 'The Request VIP - IPv4 can not change to a Request VIP - IPv6',
    298: 'The Request VIP - IPv6 can not change to a Request VIP - IPv4',
    299: 'Network already activated',
    300: 'Invalid Request VIP IP version, try to use %s',
    301: 'IP Configuration is not registred.',
    302: 'Environment Configuration already exists',
    303: 'EquipmentAccess is not registred.',
    304: 'TypeAccess is not registred',
    305: 'Network %s don\'t have associate IPs',
    306: 'Vlan já cadastrada com o número %s',
    307: '%s',
    308: 'Não existe associação de Ip e Equipamento para o IP %s',
    309: 'Failure to remove an association between an equipment and a group because the equipment is related only to one group.',
    310: 'Não foi possível excluir o grupo %s por alguns equipamentos estarem associados apenas a este grupo. Equipamentos: %s',
    311: 'Já existe uma Vlan com o arquivo_acl = %s',
    312: 'Tipo de Equipamento com nome %s, já cadastrado.',
    313: '%s.',  # Healthcheck já cadastrado
    314: '%s',  # Erro Vlan
    315: '%s',  # Erro Vlan
    316: 'Não existe Ambiente VIP cadastrado com os valores fornecidos: finalidade - %s ,cliente - %s, ambiente - %s.',
    317: 'Ip não encontrado para equipamento %s e ambiente vip %s.',
    318: 'O Ip %s e o Equipamento %s, não estão associados.',
    319: 'There is a request VIP pointing to this %s, the %s id = %s can not be excluded.',
    320: 'There are equipment related Ips, which are not part of the Environment Ip.',
    321: 'Não há rede %s no ambiente vip fornecido.',
    322: 'Requisição de VIP %s não criada',
    323: 'Ambiente %s não pôde ser excluído pois a rede %s da vlan %s tem um ip associado com a requisição vip %s.',
    324: 'Ambiente %s não pôde ser excluído pois a vlan %s está ativa.',
    325: 'Invalid value of the priority.',
    # VipRequest Real server equipment error
    326: 'Não foi possível recuperar o equipamento %s associado a um real server.',
    # VipRequest Real server equipment ip association error
    327: 'Não foi possível recuperar o ip %s e equipamento %s associados ao real server.',
    # VipRequest Real server ip doesn't exist
    328: 'Não foi possível recuperar o IP %s associado ao real server %s.',
    329: 'Existe uma inconsistência de prioridade de real server no banco de dados.',
    330: 'Existe uma inconsistência de peso (weight) de real server no banco de dados.',
    331: 'Existe uma inconsistência de portas de real server no banco de dados.',
    332: 'Existe uma inconsistência na requisição vip, o parâmetro %s é inválido. Valor: %s.',
    # 333:'Alteração de real server realizada com sucesso, mas ocorreram
    # erros de script com o(s) real(s) %s e ip(s) %s.',
    333: 'Alteração de real server concluída com falha, ocorreram erros de script com o(s) real(s) %s e ip(s) %s.',
    334: '%s',
    335: 'Existe uma rede com mesma faixa relacionada com ambiente vip',
    336: u"Não foi possivel desassociar ambiente %s, pois existem ips sendo utilizados pelas requisições vip's. IPv4[ %s ] - IPV6[ %s ]",
    337: 'Valor do parâmetro %s inválido. Valor: %s.',
    338: 'Ocorreu um erro ao salvar o filtro no banco de dados. Verifique se o nome é único.',
    339: 'Não foi possível recuperar o filtro especificado do banco de dados.',
    340: 'Ocorreu um erro ao salvar o filtro editado no banco de dados.',
    341: 'Ocorreu um erro ao remover o filtro no banco de dados.',
    342: 'Não foi possível recuperar o tipo de equipamento especificado do banco de dados.',
    343: 'A associação entre o filtro %s e o tipo de equipamento %s já existe.',
    344: '%s',
    345: u"Não foi possivel remover o equipamento %s, pois existem ips sendo utilizados por requisições vip's. IPv4[ %s ] - IPV6[ %s ]",
    346: u"Um dos equipamentos associados com o ambiente desta rede também está associado com outro ambiente que tem uma rede com essa mesma faixa, adicione filtros nos ambientes se necessário.",
    347: u"O equipamento que está sendo associado já possui um ip na mesma faixa em outra rede, se necessário adicione filtros nos ambientes.",
    348: u"O tipo de equipamento %s não pode ser desassociado do filtro %s.",
    349: u"O filtro %s não pode ser desassociado do ambiente pois está em uso.",
    350: 'Permissão %s não cadastrada.',
    351: 'Permissão Administrativa com função %s já cadastrada.',
    352: u"Não foi possível desassociar o ip %s do equipamento %s pois o ip está sendo utilizado na requisição vip %s e o equipamento é o único balanceador associado a este ip.",
    353: 'Valores duplicados para Porta Real, Porta Vip e IP do Real na mesma Requisição VIP.',
    354: 'Não foi possível excluir o ip de id %s pois ele está sendo usado em uma requisição VIP.',
    355: 'Não foi possível excluir a rede de id %s pois há um ip nela sendo usado em uma requisição VIP.',
    356: 'Não foi possível excluir a vlan de id %s pois há uma rede que possui um ip sendo usado em uma requisição VIP.',
    357: 'Esse ambiente já possui blocos cadastrados.',
    358: 'Regra inválida ou não cadastrada.',
    359: 'Bloco inválido ou não cadastrado.',
    360: 'Essa requisição vip não possui uma regra.',
    361: 'Esse bloco já está cadastrado na regra.',
    362: 'A regra relacionada a esse vip não possui blocos previamente cadastrados.',
    363: 'Não foi possível remover a rede pois ela está inativa.',
    364: 'Acl não foi criada',
    367: 'O ambiente desta Vlan já possui uma ACL com o nome = %s',
    368: 'Nao foi possivel remover a vlan pois ela esta inativa.',
    369: 'Nao foi possivel remover a vlan pois as seguintes redes nao puderam ser removidas: %s.',
    370: 'Nao foi possivel excluir o vip %s. Remova-o dos equipamentos primeiro.',
    371: 'Bloco não pode ser adicionado porque já existe uma regra para ser aplicada e o valor do parametro override é zero.',
    372: 'Server Pool Does Not Exists',
    373: 'Equipamento(s) do Server Pool: %s não pertence ao mesmo ambiente do Ambiente Vip: %s.',
    374: 'Está requisição vip não possui nenhum server pool cadastrado.',
    375: 'Pool can not be excluded because it is associated with a VIP',
    376: 'Numero de Rack %s ja existe.',
    377: 'Endereco MAC invalido',
    378: 'Rack nao pode ser incluido',
    379: 'Rack nao existe',
    380: 'Arquivo de configuracao do equipamento %s criado',
    381: 'Nome %s ja existe.',
    382: 'Os arquivos de configuracao do Rack %s nao podem ser gerados. %s',
    383: 'Nao foi possivel aplicar a configuracao do rack %s. %s',
    384: 'Erro ao editar ServerPool: %s',
    385: 'Não foi possível desassociar o ip %s do equipamento %s pois o ip está sendo utilizado nos server pools (id:identifier) %s.',
    386: 'Não foi possível excluir a rede %s pois o ip %s contido nela esta sendo usado nos Server Pools (id:identifier) %s.',
    387: 'Não foi possível excluir a vlan %s pois ela possui a rede %s e essa rede possui o ip %s contido nela, e esse ip esta sendo usado nos Server Pools (id:identifier) %s.',
    389: 'Não foi possível excluir o vip %s pois o ip %s do mesmo esta sendo usado nos Server Pools (id:identifier) %s.',
    390: 'Não foi possível excluir o vip %s pois os seguintes vips %s estão usando o mesmo ip %s.',
    391: 'Failure accessing Foreman server: %s',
    392: 'Environment is already associated with the environment vip',
    393: 'Environment is not associated with the environment vip',
    394: 'O ambiente %s não pode ser desvinculado pois existem server pools com reals vinculados a este ambiente.',
    396: 'A operação não pode ser realizada pois o ambiente "%s" do ip %s não possui permissão com um dos ambientes vips "%s".',
    397: 'O Rack, que o servidor está, não foi cadastrado.',
    400: 'Nao foi possivel adicionar o Rack',
    401: 'As mudancas nao foram salvas',
    405: 'Channel não pode ser criado. %s',
    406: 'Channel não pode ser editado. %s',
    407: 'Erro ao remover a variável.',
    410: 'Channel não pode ser deletado. %s',
    413: 'Interface não pode ser desconectada. Remova o Port Channel primeiro.',
    414: 'A rede a ser cadastrada não pertence a rede do ambiente. Cadastre o range desejado no ambiente',
    415: 'O ambiente não está configurado. É necessário efetuar a configuração.'
}


def error_dumps(code, *args):

    if isinstance(code, tuple):
        code = code[0]

    message = error_messages.get(code, '')
    if len(args) > 0:
        message = message % args

    error_map = dict()
    error_map['codigo'] = '%04d' % code
    error_map['descricao'] = message

    map = dict()
    map['erro'] = error_map

    return xml_utils.dumps_networkapi(map)


if __name__ == '__main__':
    print error_dumps('0001', 'Falha ao acessar a fonte de dados')
    print error_dumps(1)
    print error_dumps(3, 'Causa')
    print error_messages[99]
